#!/usr/bin/env python3
"""Put Fourth Player on the Kodi home menu, next to the other tools.

Kodi finds the add-on on its own -- it appears under Program add-ons as soon as
Kodi restarts. What it does not do is put it on a *custom* home menu, and a
skin-shortcuts menu like kodi-retrobox's is exactly that: a list somebody built
by hand, which nothing new joins by itself.

This edits that list as text rather than through an XML parser, because
rewriting the file with ElementTree reformats all twenty-odd entries somebody
arranged, and a diff of the whole menu is a poor way to add one line to it.

Safe to run twice: it looks for the entry before adding it.

**Not for kodi-retrobox.** That project generates this menu from its own game
library (`bin/kodi_menu.py`, run after every games sync), so an entry added
here is wiped within ten minutes and certainly by the next reboot. It carries
its own Fourth Player entry instead, and this script steps aside when it sees
one. Everyone else -- a plain Kodi with a skin-shortcuts menu somebody arranged
by hand -- is what this is for.

**Stop Kodi first.** Kodi keeps this menu in memory and writes it back out when
it exits or reloads its skin, so an edit made underneath a running Kodi is
quietly reverted -- which is exactly what happened the first time: the entry
appeared, worked, and was gone an hour later with the file byte-identical to
its backup. It refuses to run while Kodi is up unless you insist.

    install/add-kodi-menu.py            add it
    install/add-kodi-menu.py --remove   take it out again
    install/add-kodi-menu.py --force    do it anyway, and restart Kodi yourself
"""

import argparse
import os
import shutil
import subprocess
import sys
import time

MENU = os.path.expanduser(
    "~/.kodi/userdata/addon_data/script.skinshortcuts/mainmenu.DATA.xml")

ENTRY = """	<shortcut>
		<defaultID>fourthplayer</defaultID>
		<label>FOURTH PLAYER</label>
		<label2>PLAY WITH FRIENDS</label2>
		<icon>{icon}</icon>
		<thumb />
		<action>RunScript(script.fourthplayer)</action>
	</shortcut>
"""

# Its own tile first. The one below it is MULTIPLAYER's, which is a different
# thing -- who is on the sofa, rather than somebody who is not in the
# building -- and using it made two rows of the menu the same picture.
ICONS = [
    os.path.expanduser("~/.kodi/media/consoles/_fourthplayer.png"),
    os.path.expanduser("~/.kodi/media/consoles/_multiplayer.png"),
    "special://skin/extras/icons/DefaultAddonProgram.png",
]

# Sit with the other tools rather than among the consoles.
AFTER = ("RunScript(script.usbip)", "RunScript(script.bluetooth)",
         "RunScript(script.joyshock)")


GENERATORS = ("~/.local/bin/kodi_menu.py",)


def menu_generator():
    """A script that rebuilds this menu, if one is installed."""
    for candidate in GENERATORS:
        path = os.path.expanduser(candidate)
        if os.path.exists(path):
            return path
    return None


def kodi_running():
    try:
        return subprocess.run(["pgrep", "-x", "kodi.bin"],
                              capture_output=True, timeout=10).returncode == 0
    except (OSError, subprocess.TimeoutExpired):
        return False


def icon():
    for candidate in ICONS:
        if candidate.startswith("special://") or os.path.exists(candidate):
            return candidate
    return ICONS[-1]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--menu", default=MENU)
    parser.add_argument("--remove", action="store_true")
    parser.add_argument("--force", action="store_true",
                        help="edit even though Kodi is running (restart it "
                             "immediately afterwards, or the change is lost)")
    args = parser.parse_args()

    generator = menu_generator()
    if generator and not args.force:
        print(f"This menu is generated by {generator}.\n", file=sys.stderr)
        print("Anything added here is overwritten the next time it runs -- "
              "which for kodi-retrobox\nis after every games sync, so within "
              "ten minutes.\n", file=sys.stderr)
        print("kodi-retrobox carries its own Fourth Player entry; make sure it "
              "is up to date and\nrun a sync. Nothing to do here.",
              file=sys.stderr)
        return 3

    if kodi_running() and not args.force:
        print("Kodi is running.\n", file=sys.stderr)
        print("It holds this menu in memory and writes it back when it exits, "
              "so an edit made now\nis reverted the next time Kodi shuts down "
              "or reloads its skin -- silently, and\nhours later.\n",
              file=sys.stderr)
        print("Stop Kodi, run this again, then start Kodi. Or pass --force if "
              "you are about to\nrestart it yourself.", file=sys.stderr)
        return 2

    if not os.path.exists(args.menu):
        print(f"no skin-shortcuts menu at {args.menu}", file=sys.stderr)
        print("Nothing to do -- the add-on still appears under Program add-ons.",
              file=sys.stderr)
        return 1

    with open(args.menu) as handle:
        text = handle.read()

    if args.remove:
        if "script.fourthplayer" not in text:
            print("not on the menu; nothing to remove")
            return 0
        start = text.rindex("<shortcut>", 0, text.index("script.fourthplayer"))
        end = text.index("</shortcut>", start) + len("</shortcut>\n")
        new = text[:start].rstrip("\t") + text[end:]
    else:
        if "script.fourthplayer" in text:
            print("already on the menu")
            return 0
        entry = ENTRY.format(icon=icon())
        anchor = None
        for action in AFTER:
            if action in text:
                anchor = text.index("</shortcut>", text.index(action)) + len("</shortcut>\n")
                break
        if anchor is None:
            anchor = text.rindex("</shortcuts>")
        new = text[:anchor] + entry + text[anchor:]

    backup = f"{args.menu}.before-fourth-player.{time.strftime('%Y%m%d-%H%M%S')}"
    shutil.copy2(args.menu, backup)
    with open(args.menu, "w") as handle:
        handle.write(new)

    print(f"menu updated (previous kept at {os.path.basename(backup)})")
    if kodi_running():
        print("Kodi is running: restart it NOW, or it will write this change "
              "back out.")
    else:
        print("Start Kodi and the entry will be there.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
